name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ 'gateway', 'hospital', 'urgence' ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and test ${{ matrix.module }}
      run: |
        cd ${{ matrix.module }}
        mvn -B clean install -Dmaven.test.failure.ignore
        mvn surefire-report:report
      if: contains(matrix.module, 'hospital') || contains(matrix.module, 'urgence')

    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: (contains(matrix.module, 'hospital') || contains(matrix.module, 'urgence')) && always()
      with:
        name: ${{ matrix.module }}-test-reports
        path: ${{ matrix.module }}/target/surefire-reports/

  run-services:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Run services
      run: |
        nohup java -jar artifacts/urgence/target/urgence-0.0.1-SNAPSHOT.jar --httpPort=8082 > urgence.log 2>&1 &
        nohup java -jar artifacts/hospital/target/hospital-0.0.1-SNAPSHOT.jar --httpPort=8083 > hospital.log 2>&1 &
        nohup java -jar artifacts/gateway/target/gateway-0.0.1-SNAPSHOT.jar --httpPort=8081 > gateway.log 2>&1 &
        
        echo "Services started. Waiting for health checks..."
        sleep 30
        
        # Health checks
        curl -f http://localhost:8081/actuator/health || exit 1
        curl -f http://localhost:8082/actuator/health || exit 1
        curl -f http://localhost:8083/actuator/health || exit 1