name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [self-hosted]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Temurin 17 with Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build gateway
        run: |
          cd gateway
          mvn -B -Dmaven.test.failure.ignore=true clean install

      - name: Build hospital
        run: |
          cd hospital
          mvn -B -Dmaven.test.failure.ignore=true clean install

      - name: Build urgence
        run: |
          cd urgence
          mvn -B -Dmaven.test.failure.ignore=true clean install

      - name: Tests hospital
        run: |
          cd hospital
          mvn -B surefire-report:report
      - name: Upload hospital test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hospital-test-results
          path: hospital/target/surefire-reports/*.xml

      - name: Tests urgence
        run: |
          cd urgence
          mvn -B surefire-report:report
      - name: Upload urgence test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: urgence-test-results
          path: urgence/target/surefire-reports/*.xml
